MONDE_LARGEUR	: int = 30                  #Largeur du monde (nombre de colonnes)
MONDE_LONGUEUR : int = 30                 #Hauteur du monde (nombre de lignes)
NB_PROIES : int = 50	        #Nombre d’herbivores au départ
NB_PREDATEUR : int = 10	        #Nombre de carnivores au départ
MAX_STEPS = 2000                 #Nombre maximal d’itérations
ENERGIE_BASE : float = 50.0         #Énergie initiale donnée à chaque animal
MAX_ENERGIE : float = 100.0
COUT_DEPLACEMENT	: float = 1.0               #Coût énergétique d’un déplacement
GAIN_NOURRITURE : float = 3.0          #Gain de d'énergie après s'être nourr
MIN_REPRODUCTION : float = 28.0	#Énergie minimale pour se reproduire
COUT_REPRODUCTION : float = 18.0          #Coût d'energie à la reproduction
P_PREDATION : float = 0.25              #Probabilité qu'un prédateur chasse sa proie
P_REPRODUCTION_PROIES : float=0.4           #Probabilité de reproduction pour deux prédateurs proches l'un de l'autre 
P_REPRODUCTION_PREDATEURS : float=0.2          #Probabilié de reporductiob pour deux proies proches l'un de l'autre 
P_POUSSE_PLANTES : float = 0.08       #Probabilité qu'une plante pousse